name: Mirror Basilisk to GitHub

on:  
  schedule:
    - cron: '0 0 */2 * *'  # every other day at midnight
  workflow_dispatch:

jobs:
  clone-basilisk-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Install git
        run: sudo apt-get install git

      - name: Clone Basilisk repo
        run: git clone --bare https://repo.palemoon.org/Basilisk-Dev/Basilisk.git

      - name: Push Basilisk to GitHub
        run: cd Basilisk && git push --mirror https://github:${{ secrets.BASILISK_REPO_TOKEN }}@github.com/basilisk-dev/basilisk-mirror
