name: Mirror Slackware 14.2 Docker Container to GitHub

on:  
  schedule:
    - cron: '30 7 * * *'  # every day at 7:30 UTC
  workflow_dispatch:

jobs:
  clone-slackbuild-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Install git
        run: sudo apt-get install -y git

      - name: Clone repo
        run: git clone --bare https://repo.palemoon.org/Basilisk-Dev/Slackware-14.2-UXP-Docker-Builder.git

      - name: Push to GitHub
        run: cd Slackware-14.2-UXP-Docker-Builder.git && git push --mirror https://github:${{ secrets.DOCKER_SLACKWARE_TOKEN }}@github.com/Basilisk-Development-Team/Slackware-14.2-UXP-Docker-Builder-mirror
